version: "3"

services:
  doctordb:
    image: postgres:13
    container_name: doctordb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: doctor
    ports:
      - '${DB_MASTER_EXPOSED_PORT:-54320}:5432'
    volumes:
      - doctorData:/var/lib/postgresql/data

  doctorpgadmin:
    container_name: doctorpgadmin
    image: dpage/pgadmin4
    links:
      - doctordb
    depends_on:
      - doctordb
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - doctorpgadmin:/root/.pgadmin
      - doctorpgadmin:/var/lib/pgadmin
    ports:
      - '5050:5050'

  doctorserver:
    build:
      context: ./services
      dockerfile: ./Dockerfile
    container_name: doctorserver
    command: sh -c "./wait-for-it.sh -t 0 doctordb:5432 --strict -- npm run start:prod"
    depends_on:
      - doctordb
    environment:
      APPHOST: localhost
      APPPORT: 7080
      DBHOST: doctordb
      DBPORT: 5432
      DBUSERNAME: postgres
      DBPASSWORD: 123
      DBDATABASE: doctor
      DBSCHEMA: public
      DBRATETABLE: doctor
    expose:
      - 7080

  doctorclient:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: doctorclient
    depends_on:
      - doctorserver
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    depends_on:
      - doctorserver
      - doctorclient
    restart: always
    ports:
      - '8080:80'

volumes:
  doctorData:
  doctorpgadmin:
